### ISSUE TITLE
Decide on strategy for forgot password

### ISSUE THREAD

**Issue by abishekaditya** [TechUniv2018/WalletProject#26]

**Comment by siddharth-lakhara** [comment]
1. When clicked on forgot password, user is asked for email address / mobile number
2. user gets OTP on mobile and reset link on mail. The OTP is saved somewhere in DB
3. The OTP/token will be saved in the DB against the user id. This OTP will expire within a set time
4. User will be directed to another endpoint for password reset
5. User will be asked to enter the OTP/token to get a random password. This password will be updated in DB for the user
6. User can login from this temporary password
