### ISSUE TITLE
Choose an Authentication Framework

### ISSUE THREAD

**Issue by abishekaditya** [TechUniv2018/WalletProject#3]

**Comment by ahamedshoaib** [comment]
closes #1

**Comment by abishekaditya** [comment]
@rambsuthar @ahamedshoaib @brahmbhatt @siddharth-lakhara 

Moving forward with [hapi-auth-jwt](https://www.npmjs.com/package/hapi-auth-jwt) 

#### Reason: 
* hapi integration unlike passport which is express based
* simple plugin interface
* uses JWT for making API RESTful
